# Generated by Django 3.2.4 on 2021-06-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, default='media/default.jpg', upload_to='media'),
        ),
    ]
